"""
Django settings for StudyHub project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/

Configuration of my project is done in this file.
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Absulate path of the project directory is stored in BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dhb147g*c-5k&9=b9b)$^k(rf)$*8i17bb&@7u=q+9j&p1uojw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# For development purpose, DEBUG is set to True 
# To Display the details error of the pages in the browser 

# Domain or host name Django site can serve
ALLOWED_HOSTS = []



# Application definition

INSTALLED_APPS = [
    # Default built in applications
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    # Django by default has session based authentication
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # My custom application
    'Base.apps.BaseConfig',
    'rest_framework',
    'corsheaders'

]

AUTH_USER_MODEL = 'Base.User'

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'StudyHub.urls'

TEMPLATES = [
    {   
        # The template backend to use.
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Directories where Django will look for templates source files, in search order.
        'DIRS': [
            BASE_DIR / 'Templates',
            BASE_DIR / 'Base/Templates',
            
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StudyHub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Define the database to use in the project
# In this case, we are using SQLite database as default.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# If you want to use PostgreSQL database, you can use the following configuration as example.
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': YOUR_DB_NAME,
#         'USER': USERNAME,
#         'PASSWORD': PASSWORD_FOR_DB,
#         'HOST': 'localhost'  // in Development.
#         'PORT': '5432' // Default port for postgresql
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/Images/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'

]

MEDIA_ROOT = BASE_DIR / 'static/Images'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True